### ISSUE TITLE
when's the next release on puppet forge?

### ISSUE THREAD

**Issue by mattatnersc** [voxpupuli/puppet-bacula#214]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.31
- Ruby: 2.7.8
- Distribution: AlmaLinux 8
- Module version: 7.0.0

## What are you seeing

The "puppetlabs/postgresql (>= 6.4.0 < 10.0.0)" dependency is getting harder to meet as other modules up their dependency versions.  The dependencies on the master branch look good: https://github.com/voxpupuli/puppet-bacula/blob/master/metadata.json

**Comment by TheMeier** [comment]
released v8
